# Research Generator Configuration

# Data Generation Settings
data_generation:
  size: 10000
  min_length: 5
  max_length: 20
  edge_case_ratio: 0.2
  domains:
    - education
    - psychology
    - sociology
    - stem
    - humanities
  complexity_levels:
    - basic
    - medium
    - complex
  patterns:
    conversation_flow: dynamic
    noise_injection: 0.1
    include_edge_cases: true
  
  # Content Generation Parameters
  content:
    research_phases:
      - literature_review
      - methodology_discussion
      - data_analysis
      - findings_interpretation
      - implications_discussion
    
    interaction_patterns:
      - question_answer
      - elaboration_request
      - clarification_exchange
      - critical_discussion
    
    authenticity:
      min_citations: 2
      required_methodology: true
      theoretical_framework: true
      source_verification: true

# Model Architecture
model:
  architecture:
    type: transformer
    hidden_size: 768
    num_layers: 12
    num_heads: 12
    intermediate_size: 3072
    dropout: 0.1
    max_sequence_length: 1024
  
  feature_extractors:
    - semantic_analyzer
    - citation_analyzer
    - methodology_analyzer
    - theoretical_analyzer
  
  heads:
    trust:
      type: regression
      layers: [384, 192, 1]
    authenticity:
      type: classification
      layers: [384, 192, 4]
    bias:
      type: multi_label
      layers: [384, 192, 5]

# Training Configuration
training:
  batch_size: 32
  learning_rate: 2.0e-5
  max_lr: 1.0e-4
  epochs: 10
  steps_per_epoch: 1000
  validation_split: 0.2
  
  optimization:
    optimizer: adamw
    weight_decay: 0.01
    max_grad_norm: 1.0
    warmup_steps: 1000
    gradient_accumulation: 4
    mixed_precision: true
  
  curriculum_learning:
    stages:
      - name: basic_understanding
        epochs: 2
        difficulty: 0.3
        focus: [trust_scoring, citation_verification]
      
      - name: methodology_analysis
        epochs: 3
        difficulty: 0.6
        focus: [methodology_assessment, theoretical_alignment]
      
      - name: advanced_analysis
        epochs: 5
        difficulty: 0.9
        focus: [bias_detection, quality_assessment]
    
    advancement_criteria:
      min_accuracy: 0.8
      max_loss: 0.2
      min_epochs: 2

# Evaluation Settings
evaluation:
  metrics:
    trust:
      weights:
        citation_quality: 0.3
        methodology_rigor: 0.3
        theoretical_alignment: 0.2
        evidence_strength: 0.2
      thresholds:
        high_trust: 0.8
        medium_trust: 0.6
        low_trust: 0.4
    
    bias:
      detection_threshold: 0.15
      types:
        - confirmation_bias
        - selection_bias
        - reporting_bias
        - methodology_bias
      pattern_recognition: true
    
    quality:
      aspects:
        - methodology_rigor
        - theoretical_grounding
        - empirical_evidence
        - analytical_depth
      scoring: weighted_average
  
  analysis:
    granularity: detailed
    include_recommendations: true
    track_confidence: true
    assessment_level: comprehensive

# Real-time Processing
realtime:
  processing:
    max_latency: 100  # ms
    batch_size: 1
    streaming: true
    update_frequency: message-level
  
  analysis:
    trust_threshold: 0.85
    bias_threshold: 0.15
    quality_threshold: 0.75
  
  monitoring:
    track_latency: true
    track_quality: true
    track_consistency: true

# Deployment Settings
deployment:
  environment: development  # development, staging, production
  platform: streamlit
  api_version: v1
  
  monitoring:
    latency_threshold: 100  # ms
    error_tracking: true
    performance_monitoring: true
  
  scaling:
    min_instances: 1
    max_instances: 5
    auto_scaling: true

# Logging Configuration
logging:
  level: INFO
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  handlers:
    - type: console
    - type: file
      filename: logs/research_generator.log
  
  metrics_logging:
    frequency: 100  # steps
    save_path: logs/metrics/
    include_detailed: true

# Storage Settings
storage:
  base_path: data/
  formats:
    - csv
    - json
    - parquet
  compression: gzip
  
  backup:
    enabled: true
    frequency: daily
    retention_days: 30